### PR TITLE
Windows build

### PR DESCRIPTION
**Pull request by duncanwp**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixing #16

### CODE REVIEW

**Comment by duncanwp** [comment]
@conda-forge-admin, please rerender

**Comment by duncanwp** [comment]
@ocefpaf It can't seem to import pyhdf even though it's clearly installed in the _test_env just a few lines [before](https://ci.appveyor.com/project/conda-forge/pyhdf-feedstock/builds/21860556/job/07860ekpumewfmr9#L386)...

**Comment by ocefpaf** [comment]
> @ocefpaf It can't seem to import pyhdf even though it's clearly installed in the _test_env just a few lines [before](https://ci.appveyor.com/project/conda-forge/pyhdf-feedstock/builds/21860556/job/07860ekpumewfmr9#L386)...

It is not installed. There is no build script (`bld.bat`).

**Comment by ocefpaf** [comment]
Done in #21

**Pull request closed without merging**
