### PR TITLE
WIP :: Debug PY34+Win

### PR DESCRIPTION
**Pull request by ocefpaf**
Debugging the Windows builds for Python 3.4 that are failing.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@gillins if you find some time can you take a look at the Windows failures here. (Very low priority BTW.)

**Comment by gillins** [comment]
In `bld.bat` try changing `set LIBRARY_DIRS=%LIBRARY_BIN%` to %LIBRARY_LIB%. It should find the import libraries it needs there.

I'm not sure why some of those builds are working, but they seem to have the right path set in addtion. Weird.

**Comment by gillins** [comment]
Oh no - now they are all failing. Perhaps you can't set both?
Does it work if you just set to `LIBRARY_LIB`?

**Comment by ocefpaf** [comment]
@gillins only one failed too https://github.com/conda-forge/pyhdf-feedstock/pull/3#

This is low priority. I never really had a request to get this working on Windows :smile:

**Comment by ocefpaf** [comment]
> Oh no - now they are all failing. Perhaps you can't set both?

@gillins your suggestion seems to work after I rebased! :tada:

**Comment by gillins** [comment]
Might be something to do with the conda-build unpinning..... :+1:

**Comment by ocefpaf** [comment]
Yeah, this is so old that a lot has changed in conda-build. I guess the thanks should go to @msarahan and his many releases :wink:

**Pull request merged**
